### PR TITLE
External Tables: Incorrect handling of "time with time zone" values 

### LINKED ISSUE #67: External Tables: Incorrect handling of "time with time zone" values
mantis issue 8763

drop table if exists int \g
drop table if exists ext \g

create table int (timetz time with time zone, timestamptz timestamp with time zone) \g
create external  table ext (timetz time with time zone, timestamptz timestamp with time zone) using spark 
with reference='hdfs://nlam-cluster06:8020/user/adrian/external_tables/timezone.parquet'\g [^]

insert into int values ('12:00:00+02:00', '2010-10-10 12:00:00+02:00') \g
insert into ext values ('12:00:00+02:00', '2010-10-10 12:00:00+02:00') \g

select \* from int \g
select \* from ext \g

Results in:

???????????????????????????????????????????????????????????????????????????????????
?timetz                         ?timestamptz                                      ?
???????????????????????????????????????????????????????????????????????????????????
?12:00:00+02:00                 ?2010-10-10 12:00:00.000000+02:00                 ?
???????????????????????????????????????????????????????????????????????????????????
(1 row)

???????????????????????????????????????????????????????????????????????????????????
?timetz                         ?timestamptz                                      ?
???????????????????????????????????????????????????????????????????????????????????
?08:00:00+00:00                 ?2010-10-10 10:00:00.000000+00:00                 ?
???????????????????????????????????????????????????????????????????????????????????
(1 row)

The raw file data seems to be wrong too, but with no obvious explanation:

+--------------------+--------------------+
|              timetz|         timestamptz|
+--------------------+--------------------+
|1970-01-01 09:00:...|2010-10-10 12:00:...|
+--------------------+--------------------+

### PR DESCRIPTION
**Pull request by cbarca**
- Fixed handling of TZ offset in time and timestamps by not subtracting it from the value since X100 already does that
- Fixed bug with the BigInteger mask, used to be formatted in LittleEndian (instead of BigEndian)

Fixes #67

### CODE REVIEW

File: src/main/scala/com/actian/spark_vector/colbuffer/timestamp/TimestampColumnBuffer.scala [hunk 1]
```diff
@@ -86,15 +86,16 @@ private class TimestampTZConverter extends TimestampConversion.TimestampConverte
   private final val TimeMaskBI = new BigInteger(timeMask)
   private final val SecondsInMinuteBI = BigInteger.valueOf(SecondsInMinute)
 
-  /** Set the 117 most significant bits to 1 and the 11 least significant bits to 0. */
+  /** Set the 117 most significant bits to 1 and the 11 least significant bits to 0.
+   *  @note the mask has to be in BigEndian due to its use on BigIntegers */
   private def timeMask: Array[Byte] = {
```
Comment (and-costea) [inline src/main/scala/com/actian/spark_vector/colbuffer/timestamp/TimestampColumnBuffer.scala]: I don't really see the use of this anymore. In convert we shift by 11 bytes and so the and(TimemaskBI) would at most lose some of the most significant bits (which I think would be a bug to do so). I think we can remove it.

**Comment by and-costea** [comment]
Ship it after testing it.
